name: Crowdin Upload branches

on:
  workflow_dispatch:
  push:
    branches:
      - stable/*
jobs:
  upload-crowdin-branch:
    name: CI Build
    uses: Meeds-io/meeds-actions/.github/workflows/upload-crowdin-branches.yml@develop
    with:
      YML_CROWDIN_LANGUAGES_ARG: ${{vars.YML_CROWDIN_LANGUAGES_ARG}}
    secrets:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
